### ISSUE TITLE
test 2

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#25]
Create script test_2.py which will test the following scenario:

  * Go to "https://en.wikipedia.org/wiki/Main_Page" page
  * Use search box to search for: "unit testing" 
  * Verify that you are on the page "Unit Testing"
  * Click on the link: "halting problem"
  * Verify that the page contain phrase: "Turing machine"
  * Verify that the page doesn't contain phrase: "no needed"

**Comment by AnnaLangner** [comment]
Should I use a function and classes to write this code?

**Comment by klangner** [comment]
Functions yes. Classes no.

**Comment by AnnaLangner** [comment]
How else can I find something in the string?

by xpath??

You said: `There is function find on String. But if you are looking to find something inside DOM then path is good approach.` 
If I don't understand correctly, correct me. When I search for a paragraph or div, I use the path, when I search for a string, I use the find function. Yes?

**Comment by klangner** [comment]
When you search for any DOM element like <p> <div> etc. Then you need to use xpath. This is probably what you need here.
But when you have text as String and want to find something inside string, then you can use `find()` function.

**Comment by AnnaLangner** [comment]
I schould verify that the page contain or don't contain phrase. 

Is it done in the same way? because I can't find the answer.

**Comment by klangner** [comment]
Yes the same but in one case you should find it and return true and in the later case check that search returns false.

**Comment by AnnaLangner** [comment]
My code looks  like this:

```
def main():
  driver = webdriver.Chrome(executable_path="bin/chromedriver")
  driver.get("https://en.wikipedia.org/wiki/Main_Page")
  search_input = driver.find_element_by_id("searchInput")
  search_input.clear()
  search_input.send_keys("Unit testing")
  search_input.submit()
  assert "Unit testing" in driver.title
  searched_link = driver.find_element_by_link_text("halting problem")
  searched_link.click()
  phrase_1 = driver.find_elements_by_xpath("//*[contains(text(), 'Turing machine')]")  
  print(type(phrase_1))
  print(phrase_1)
  # assert len(phrase_1) > 0
  phrase_2 = driver.find_elements_by_xpath("//*[contains(text(), 'no needed')]") 
  print(type(phrase_2))
  print(phrase_2)
  # assert len(phrase_2) <= 0
  # driver.close()


main()
```

prints looks like this: 

```
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:59039/devtools/browser/3caf3de3-052d-4de2-874d-e58655106079

<class 'list'>
[<selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", 
element="1e0033bd-9b4d-41b0-8f59-7866dee1114c")>, <selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", element="ff2fe2c3-fe36-4d27-b73e-6b21c83dd65d")>, <selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", element="8ba24e46-2950-4046-9bb8-18876add163e")>, <selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", element="2f93ff0c-6c0b-4637-9a24-46c29c828ec5")>, <selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", element="75003e85-5748-4963-b412-aa904062b641")>, <selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", element="3612589b-9523-4781-a133-45599b59c340")>, <selenium.webdriver.remote.webelement.WebElement (session="e2c67135dd0d428b80a8d70c6209b040", element="c16c05ac-9fe5-49f5-aa9b-ac3e1e89bf7b")>]

<class 'list'>
[]
```

Is this correct? It's weird because sometimes it returns an empty list, and sometimes something like that...

**Comment by klangner** [comment]
Yes it looks ok.
To be sure you can also print the first element of the first list and check its text.
But it is not necessary to finish this code.

**Comment by AnnaLangner** [comment]
I think I have a bad xpath.
that's why I get an empty list in the first case.
But I don't know how to change it :(

**Comment by AnnaLangner** [comment]
I changed the code like this:
```
  phrase_1 = driver.find_elements_by_xpath("//*[text()='Turing machine']")
  print(phrase_1[0])
  assert len(phrase_1) > 0
```

and I get every second call good answer:

```
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:62422/devtools/browser/0754f69d-78e3-457d-905e-2e28f9974e62    
<selenium.webdriver.remote.webelement.WebElement (session="5662fc9cd12d9f1218a20bae1d54d9c6", element="d3f1e270-7d4b-4471-a95a-47677a4569af")>

annal@LAPTOP-MN5V2CJL MINGW64 /d/Programowanie/pysandbox (selenium2)
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:62481/devtools/browser/b5b92247-0c6d-4cbf-9a75-95c393c7b1bf    
Traceback (most recent call last):
  File "script/test_2.py", line 25, in <module>
    main()
  File "script/test_2.py", line 16, in main
    print(phrase_1[0])
IndexError: list index out of range

annal@LAPTOP-MN5V2CJL MINGW64 /d/Programowanie/pysandbox (selenium2)
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:62506/devtools/browser/1b10ecec-a791-4bde-abab-4fb897e7af13    
<selenium.webdriver.remote.webelement.WebElement (session="603a013c1bf42434696bcf5e567dd69e", element="496b0607-3706-4e83-894b-333a3984b9c0")>

annal@LAPTOP-MN5V2CJL MINGW64 /d/Programowanie/pysandbox (selenium2)
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:62534/devtools/browser/972ace63-9a09-4c85-9e5a-7f825b73c640    
Traceback (most recent call last):
  File "script/test_2.py", line 25, in <module>
    main()
  File "script/test_2.py", line 16, in main
    print(phrase_1[0])
IndexError: list index out of range

annal@LAPTOP-MN5V2CJL MINGW64 /d/Programowanie/pysandbox (selenium2)
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:62562/devtools/browser/be76854c-700c-4efb-9075-358a6952e681    
<selenium.webdriver.remote.webelement.WebElement (session="1472883bdd392c8def9af5495c80a889", element="dbf2dd14-0134-4f5e-b24e-3e11cdd2b4bb")>
```

**Comment by klangner** [comment]
The problem is that probably you red values before page is fully loaded. Check this link for more information and some solutions:
https://selenium-python.readthedocs.io/waits.html

**Comment by AnnaLangner** [comment]
```
  searched_link = driver.find_element_by_link_text("halting problem")  
  wait = WebDriverWait(driver, 40)
  searched_link = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, 'halting problem')))
  searched_link.click()
```
I tried with element_to_be_clickable and it doesn't work :(  I changed the waiting time from 10 to 100, but it doesn't matter. I I tried different methods but it doesn't work  :|

I checked that this link is always found, but it is not always clicked

**Comment by klangner** [comment]
The problem probably is not on this page but on the next one. After you click on the link try to wait till page is ready before looking for the text.

**Comment by AnnaLangner** [comment]
I don't understand it ... I changed this code:
```
  searched_link = driver.find_element_by_link_text("halting problem")
  wait = WebDriverWait(driver, 10)
  searched_link = wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "halting problem")))
  searched_link.click()
  phrase_1 = driver.find_elements_by_xpath("//*[text()='Turing machine']")
  phrase_1 = wait.until(EC.presence_of_element_located((By.XPATH, "//*[text()='Turing machine']")))
```
three times went well, but the fourth time I have this error:
```
$ python script/test_2.py

DevTools listening on ws://127.0.0.1:52570/devtools/browser/ee216453-1468-407f-9d7a-63b949b80db5    
Traceback (most recent call last):
  File "script/test_2.py", line 30, in <module>
    main()
  File "script/test_2.py", line 21, in main
    phrase_1 = wait.until(EC.presence_of_element_located((By.XPATH, "//*[text()='Turing machine']")))
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by AnnaLangner** [comment]
```
  searched_link = driver.find_element_by_link_text("halting problem")
  time.sleep(10)
  searched_link.click()  
  phrase_1 = driver.find_elements_by_xpath("//*[text()='Turing machine']")
  time.sleep(10)
  print(phrase_1)
  assert len(phrase_1) > 0
```
In this case it works

**Comment by klangner** [comment]
Ok. Now lets try to remove one of the sleeps and check if it still works.
Are both needed?

**Comment by AnnaLangner** [comment]
I checked the code and only the link must have sleep () function

**Comment by klangner** [comment]
Could you commit working code to the github so I can have a look at it?

**Comment by AnnaLangner** [comment]
yes

**Comment by klangner** [comment]
Ok. Now it doesn't work again. So my question is why?
Analyze the console output and try to explain what is wrong. First which instruction failed?

**Comment by AnnaLangner** [comment]
I'm getting an empty list again.
When I checked what's in WebDriverWait
in this way:
```
  searched_link = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "halting problem")))
  print(type(searched_link.get_attribute("innerHTML")))
```
I get a string... should it be a string?

**Comment by AnnaLangner** [comment]
Maby the problem is in this "Page preview" , when you want to click a link and hover over the link shows a quick preview of the topic while reading the page? 
I have no more ideas :(

**Comment by klangner** [comment]
It looks that there is a bug in chrome driver:
https://github.com/SeleniumHQ/selenium/issues/4075

The best solution is to use javascript to click on elements. Example:
```python
driver.execute_script("arguments[0].click();", searched_link)
```

**Comment by AnnaLangner** [comment]
oki :)
