### ISSUE TITLE
test_2 firefox

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#29]
Modify script test_2 so it will use Firefox driver instead of chrome.
Then add parameter to the script which will decide which driver to use. E.g
```sh
python script/test_2.py --driver firefox
```
will use Firefox driver
If no parameter is provided then by default use Firefox

**Comment by AnnaLangner** [comment]
I have a problem with geckodriver.... I have an error : 
```
$ python script/test_2.py 
Traceback (most recent call last):
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__        
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child 
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script/test_2.py", line 23, in <module>
    main()
  File "script/test_2.py", line 6, in main
    driver = webdriver.Firefox(executable_path="bin/geckodriver")
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```
it is the same when I had the wrong path ... but now I have the right path ...

I thought it was because the file is not executable. But it is.

**Comment by AnnaLangner** [comment]
It's working now

**Comment by klangner** [comment]
Well done with the first part of the issue. Now lets add command line argument to decide which driver to use.

**Comment by AnnaLangner** [comment]
I think I'm almost done. 
I have two problems:
1. When I run the script with --diver firefox or without an argument, chrome is also displayed, but nothing happens there. Is there any way to block chrome?
2. When I run the script from --driver chrome, I get a WebDriverWait error :
```
$ python script/test_2.py --driver "chrome"

DevTools listening on ws://127.0.0.1:60079/devtools/browser/36b29f9e-238f-4919-a5ab-1a9cb3c51db0
Traceback (most recent call last):
  File "script/test_2.py", line 39, in <module>
    main()
  File "script/test_2.py", line 27, in main
    WebDriverWait(driver, 10).until(EC.url_changes(driver.current_url))
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until     
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```
Should you use time.slepps in this case to work around this error?

Do push?

**Comment by klangner** [comment]
Yes, please push the code so I can take a look at it.

**Comment by klangner** [comment]
You shouldn't create 2 drivers at the beginning. Create only one driver.

**Comment by AnnaLangner** [comment]
like this? :
```
  driver = {
    'firefox' : 'webdriver.Firefox(executable_path="bin/geckodriver.exe")',
    'chrome' : 'webdriver.Chrome(executable_path="bin/chromedriver")'
  }
```

ok I changed this like You said in PR

**Comment by klangner** [comment]
This will create dictionary not driver. But it is ok now.
